### ISSUE TITLE
Instantiate quantizers by name

### ISSUE THREAD

**Issue by vloncar** [google/qkeras#10]
Quantizers in layers can be specified either as an instance, or as a string that gets evaluated. For example `QDense(10, kernel_quantizer=ternary(), ...)(x)` or `QDense(10, kernel_quantizer='ternary()', ...)(x)` but not `QDense(10, kernel_quantizer='ternary', ...)(x)`. Making sure that  an instance is returned in [safe_eval.py](https://github.com/google/qkeras/blob/master/qkeras/safe_eval.py#L86) seems to fix this, but I am wondering does this have any downsides?

**Comment by nunescoelho** [comment]
Safe eval is a version of eval that does not allow users to run malicious
code.

It enables one to do things like "quantizer(VARIABLE,
parameter=VARIABLE2)", or at least "quantizer(3, parameter=True)".

Claudionor

**Comment by vloncar** [comment]
I understand that. What I am suggesting is that if users specify quantizer just by name, e.g., `binary`, `safe_eval` should interpret it as `binary()` (without parameters). Ifthe user wants to parametrize the quantizer, the syntax you mentioned still remains. I think this is more intuitive and more in line with what users expect coming from vanilla Keras. I can make a PR for this.

**Comment by zhuangh** [comment]
Hi @vloncar 

Could you make a PR for that so that I can take a look? It should be a simple API change, only use binary's or ternary's default parameters. 

Thanks!
