### ISSUE TITLE
How low precision weights and biases are stored in QKeras?

### ISSUE THREAD

**Issue by wilfredkisku** [google/qkeras#103]
Being new to quantization in QKeras, is there a way I can get the quantized weights and know how they are exactly stored?

If the (min, max) values for scaling have been used how can I extract those values to verify the effective quantization in each layer?

Thanks.

**Comment by jurevreca12** [comment]
QKeras stores the weights in floating-point. So they are "stored" exactly as in regular keras. What qkeras does is apply "fake quantization functions" that have the signature _f:Tensor[float]->Tensor[float]_. But the output is constrained to the values that a quantized weight could take. I suggest you begin with taking a look at the different quantization functions (quantized_bits, binary...)

**Comment by wilfredkisku** [comment]
Thanks. I am able to understand the quantization technique that has been used by looking at the functions. Is there a way to store the quantized weights during each epoch of the training phase?

**Comment by jurevreca12** [comment]
ah. I see. Well you can look at the weights as such:` layer.kernel_quantizer_internal(layer.kernel)`.

**Comment by wilfredkisku** [comment]
Thanks! works like a charm.
