### ISSUE TITLE
Using qkeras layers concurrently with Tensorflow's pruning tools. 

### ISSUE THREAD

**Issue by Duchstf** [google/qkeras#11]
Hello, very cool project!!

I'm just wondering if it would be possible to train the model using qkeras layers with the pruning tools in [Tensorflow's model optimization package](https://www.tensorflow.org/model_optimization/guide/pruning/pruning_with_keras). For example, can we have something like this?

```
tf.keras.Sequential([
    sparsity.prune_low_magnitude(
        l.QConv2D(32, 5, padding='same', activation='relu'),
        input_shape=input_shape,
        **pruning_params)])
```

Thanks,

Duc.

**Comment by zhuangh** [comment]
@Duchstf good point, actually we have been looking into this with the team.

**Comment by vloncar** [comment]
@zhuangh Do you have an ETA for this? If you are not working on it, we can look into it, it seems straightforward to implement. I hope I'm not missing something.

**Comment by zhuangh** [comment]
No ETA yet. And for sure, if you have any things in mind, feel free to create PRs. We would be happy to review. thanks!

**Comment by zhuangh** [comment]
Hi @vloncar and @Duchstf 

I assigned this to you. Hope it is OK. Feel free to let us know if you have any questions. thanks!

**Comment by vloncar** [comment]
Hi @zhuangh, custom prunable layers rely on stuff from `tensorflow_model_optimization` which is not part of the bare tensorflow installation. Should we implement it as a hard dependency or do we go for the monkeypatched version so that this functionality is avaliable only when `tensorflow-model-optimization` package is installed?

**Comment by zhuangh** [comment]
we could use tensorflow_model_optimization as dependency when installing qkeras. Let me know if you have any concern.

**Comment by zhuangh** [comment]
Merged and close this issue!
