### ISSUE TITLE
Quantized operation during inference?

### ISSUE THREAD

**Issue by Duchstf** [google/qkeras#15]
Hello,

I just have a question about the `qlayers` during inference time here. So after training, the weights of the layers are quantized. However, would the operations between different layers quantized accordingly? 

For example, you can have low bit weights but the operations between them is still 32 bits, which gives quite different hardware performance than low bit weights and low bit operations. 

Thanks,

Duc.

**Comment by zhuangh** [comment]
@Duchstf 

Maybe I have not fully understand the question. Regarding "operations" between layers, you can put 
- quantizer inside one layer like [https://github.com/google/qkeras/blob/master/examples/example_qoctave.py#L49](url)
- Or add QActivation layer before or after one layer, like 
[https://github.com/google/qkeras/blob/master/examples/example_mnist.py#L82](url)

and make the tensors to be quantized.

Let me know if I answered the wrong question.

Thanks!

**Comment by Duchstf** [comment]
Hi,

what I meant is that, for example, you have two quantized parameters: `x` and `y`. However, when you multiply them together `x*y` the result will still be a `float32` and not be quantized anymore. 

Would it happen here? and what should I do to prevent it from happening?

Duc.

**Comment by zhuangh** [comment]
Let's assume the `mac` (multiplication-and-addition) has enough bits to hold `x*y` (`mult=x*y`, `mac += mult`). Then, use that datatype to implement `mac` in hardware. 

FYI, we have been working on tool inside qkeras to derive `mac` datatype automatically. For example, when `x` is `quantized_bits(bits=4, integer=1, keep_negative=0)`, `y` is `quantized_bits(bits=2, integer=1, keep_negative=0)`, `mult` could be `quantized_bits(bits=6, integer=2, keep_negative=0)`, and set `mac` type correspondingly. There are different types of quantizers and operations, so we need to map them accordingly. This will make hardware datatype setup easy. So stay tune.

To simulate the numerical behavior, I suggest you apply `QActivation` layer or `SomeLayer(..., activation=quantizer)` to ensure the model accuracy.

 Hope it makes sense. Feel free to keep discussions in this thread!
