### ISSUE TITLE
Is it possible to quantize LSTM??

### ISSUE THREAD

**Issue by OriAlpha** [google/qkeras#20]
Can we quantize LSTM with these libraries or any ideas for implementation

**Comment by zhuangh** [comment]
Hi @OriAlpha 

Not yet. They are on our TODO list. Meanwhile, public (Github) contributions are welcome! Feel free to create pull request for that. 

cc @nunescoelho

**Comment by OriAlpha** [comment]
I would like to do some contributions but have some questions related to the quantization of LSTM. By doing quantization for the kernel, recurrent_kernel and bias weights will help fro quantization or something else that needs to be done. Any initial ideas for this approach

**Comment by zhuangh** [comment]
@jecorona97 do you have TODO to share here?

**Comment by OriAlpha** [comment]
I was working on LSTM so I thought can help

**Comment by zhuangh** [comment]
Hi @OriAlpha thanks. Good to know that!

Actually, there will be a PR from @jecorona97 about sequence model very soon, which would be a good starting point. Stay tune. 

Sorry for the late.

**Comment by OriAlpha** [comment]
> Hi @OriAlpha thanks. Good to know that!
> 
> Actually, there will be a PR from @jecorona97 about sequence model very soon, which would be a good starting point. Stay tune.
> 
> Sorry for the late.

That's nice waiting for PR

**Comment by OriAlpha** [comment]
Actually I tried something with this, a small trial 

```
for layer in model.layers:
	if layer_name == 'lstm':
	    weights = layer.get_weights()
	    kernel_weights = weights[0]
	    recurrent_kernel_weights = weights[1]
	    bias_weights = weights[2]

	    kernel_weights_fake = np.full((weights[0].shape), 1000)
	    recurrent_kernel_weights_fake = np.full((weights[1].shape), 1000)

	    qaunt_kernel_weights = weights[0] * kernel_weights_fake
	    qaunt_recurrent_kernel_weights = weights[1] * recurrent_kernel_weights_fake

	    qaunt_kernel_weights = qaunt_kernel_weights.astype(int)
	    qaunt_recurrent_kernel_weights = qaunt_recurrent_kernel_weights.astype(int)

	    new_weights = [qaunt_kernel_weights, qaunt_recurrent_kernel_weights, qaunt_bias_weights]
	    layer.set_weights(new_weights) 
```
Could this work I tried but while saving the weights. 
model.save will save the weights in float_32 again

**Comment by zhuangh** [comment]
@OriAlpha just ping you in the PR.

**Comment by zhuangh** [comment]
https://github.com/google/qkeras/pull/30 is closed. Feel free to reopen it if any problems. Thanks!
