### ISSUE TITLE
Getting 'TypeError: cannot unpack non-iterable Model object' error when trying to run example_keras_to_qkeras.py

### ISSUE THREAD

**Issue by fPecc** [google/qkeras#22]
I am getting error "TypeError: cannot unpack non-iterable Model object" when trying to run the example_keras_to_qkeras.py script.

I installed all requirements using

`pip install -r requirements.txt`

And then run

`pip install .`

And

`python setup.py install`

**Comment by vloncar** [comment]
A fix for this was included in #21

**Comment by zhuangh** [comment]
Hi @fPecc, since @vloncar pointed out the fix. I closed this isuee. Feel free to reopen it if there is still issue.
