### ISSUE TITLE
Requirements file

### ISSUE THREAD

**Issue by ricardobarroslourenco** [google/qkeras#32]
I would like to know if QKeras is architecture agnostic (following TF requirements) since it lists as import the standard `tensorflow` python library (I assume if that is correct, `tensorflow-gpu`would be supported as well).

**Comment by zhuangh** [comment]
Hi Richardo @ricardobarroslourenco 

Sorry for the late reply. based on what I heard from the teammates using gpu, it should work with code, but quantized network is not optimized to run fast in gpus for inference.

**Comment by ricardobarroslourenco** [comment]
Ok. No problems. I was more concerned on the training portion.
