### ISSUE TITLE
print_qstats(sho_fitter.model)

### ISSUE THREAD

**Issue by FJOlugbodi** [google/qkeras#33]
Hello, I tried to quantize a simple harmonic oscillator fitter model, but when I tried to few the stats of the layers in the model, an error occurred. I was hoping that you guys may have a solution? The method seems to be having trouble primarily with the quantizers of the dense layers--quantized_bits specifically, but I do not understand much more than that.

I have attached the error message below:

`WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/qkeras/estimate.py:314: Tensor.experimental_ref (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use ref() instead.
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-7-7fcf98f404b6> in <module>()
----> 1 print_qstats(sho_fitter.model)
3 frames
/usr/local/lib/python3.6/dist-packages/qkeras/estimate.py in print_qstats(model)
    491   """Prints quantization statistics for the model."""
    492 
--> 493   model_ops = extract_model_operations(model)
    494 
    495   ops_table = defaultdict(lambda: 0)
/usr/local/lib/python3.6/dist-packages/qkeras/estimate.py in extract_model_operations(model)
    469     operations[layer.name] = {
    470         "type":
--> 471             get_operation_type(layer, cache_q),
    472         "number_of_operations":
    473             number_of_operations if isinstance(number_of_operations, int) else
/usr/local/lib/python3.6/dist-packages/qkeras/estimate.py in get_operation_type(layer, output_cache)
    293     if output_cache.get(layer.input.experimental_ref(), None) is not None:
    294       x_mode, x_bits, x_sign = get_quant_mode(
--> 295           output_cache.get(layer.input.experimental_ref()))
    296     else:
    297       print("cannot determine presently model for {}".format(layer.name))
/usr/local/lib/python3.6/dist-packages/qkeras/estimate.py in get_quant_mode(quant)
    253             mode = 4
    254       return (mode, bits, sign)
--> 255   raise ValueError("Quantizer {} Not Found".format(quant))
    256 
    257 `

**Comment by zhuangh** [comment]
@FJOlugbodi 

The warning is from tensorflow actually. We will update to ref() API instead of experimental_ref() in the future. And, do you mind sharing how you use this print_qstats, and the model caused errors? thanks!

**Comment by zhuangh** [comment]
this issue has been quite for a while. close it. feel free to reopen it if you have more questions.
