### ISSUE TITLE
`keep_negative` parameter in `quantizers.quantized_bits` should be boolean

### ISSUE THREAD

**Issue by justinchuby** [google/qkeras#37]
In https://github.com/google/qkeras/blob/a55548e34f918b0cb224e6372603f9da9f9ffd93/qkeras/quantizers.py#L318-L319

keep_negative is a boolean parameter by its context and documentation. In https://github.com/google/qkeras/blob/a55548e34f918b0cb224e6372603f9da9f9ffd93/qkeras/quantizers.py#L324

it's also converted to one. Is there a reason why its default value is 1, of type int? I might be missing something since I'm new to the package.

**Comment by zhuangh** [comment]
you are not missing anything. It was just a design choice.

**Comment by justinchuby** [comment]
I see! Is there a reason why it was designed this way?

**Comment by zhuangh** [comment]
Justin @justinchuby actually this is a good point and we change accordingly in the comment mentioned above. Thanks. Let me know if you have more question.
