### ISSUE TITLE
Int4 Quantization support

### ISSUE THREAD

**Issue by puranjaymohan** [google/qkeras#41]
Hi!
I want to get started with using this library, specifically for int4 quantization support. I have already built a model using Keras and want to quantize it to int4. Does this library have something similar to tflite converter?
Also I have used representative datasets when I used tflite for int8 quantization, does this library also require something of that sort.

Thanks

**Comment by zhuangh** [comment]
Hi @puranjaymohan 

Nice to hear from you. But we do not have tflite converter and representative datasets at this moment. 

Regarding your model, you could change your Keras model to QKeras counterpart, e.g., use qlayers, make the kernel quantizer to be quantized_bits(4,4) something like that. 

A good reference from our notebook https://github.com/google/qkeras/blob/master/notebook/QKerasTutorial.ipynb

Thank you for your interest!

**Comment by zhuangh** [comment]
close it, feel free to reopen if you have more questions
