### ISSUE TITLE
Release a new stable version

### ISSUE THREAD

**Issue by tu1258** [google/qkeras#42]
I see that there are lots of great commits since v0.8. However, people can't enjoy them without releasing a stable version. (or they have to deal with some annoying issue) Considering that there will be more and more people discovering this, releasing a new stable version would be nice!

**Comment by zhuangh** [comment]
For sure, actually we are preparing for the next release. Thanks @tu1258

**Comment by tu1258** [comment]
@zhuangh Would you mind telling me the release date? I'm gonna make my own version if the date is too far away. Thanks!

**Comment by zhuangh** [comment]
https://github.com/google/qkeras/pull/48 is pending. need to fix this first. 

cc @jecorona97 @lishanok

**Comment by zhuangh** [comment]
> #48 is pending. need to fix this first.
> 
> cc @jecorona97 @lishanok

closed #48 after merging https://github.com/google/qkeras/commit/67e7c6b8cbd6befd594f142187ac4b73b35512ac

released https://github.com/google/qkeras/releases/tag/v0.9.0

Close this issue, please do feel free to reopen this issue if you have any questions. Thanks!
