### ISSUE TITLE
Requirements to implement new quantization classes

### ISSUE THREAD

**Issue by nicologhielmetti** [google/qkeras#45]
I would like to ask what are the requirements for a new quantizer class: is it mandatory to inherit from BaseQuantizer? What should return the` __call__() `method? What is `_set_trainable_parameter()` intended for? Which are the differences between using traditional keras layers assigning `(kernel|bias)_constraint` to a quantization class with respect to qkeras layers where you can specify `(kernel|bias)_quantizer`?
Thank you in advance

**Comment by zhuangh** [comment]
_set_trainable_parameter() is a function that allow a layer to set up/overwrite the parameters of kernel_quantizer during the training.

**Comment by zhuangh** [comment]
it has been quiet for a while. close this. feel free to reopen it.
