### ISSUE TITLE
INT8 or INT16 for output feature map

### ISSUE THREAD

**Issue by linbaiwpi** [google/qkeras#49]
Hello, I am wondering is it possible to quantize the output feature map into INT8 or INT16 using QKeras? So that the memory space can be compressed as well.

**Comment by zhuangh** [comment]
Hi @linbaiwpi 

could you try quantized_bits(bits=8, integer=8) https://github.com/google/qkeras/blob/master/qkeras/quantizers.py#L275 for INT8?

**Comment by linbaiwpi** [comment]
> Hi @linbaiwpi
> 
> could you try quantized_bits(bits=8, integer=8) https://github.com/google/qkeras/blob/master/qkeras/quantizers.py#L275 for INT8?

Hi @zhuangh 
Thanks for your reply. But I am not 100% sure your suggestion. For instance, I would love to use the following layer to, and want the weights and bias are quantized into 8-bit.
_xOut = QSeparableConv2D(32, (3, 3),
             depthwise_quantizer=quantized_bits(4, 0, 1),
             pointwise_quantizer=quantized_bits(3, 0, 1),
             bias_quantizer=quantized_bits(3),
             depthwise_activation=quantized_tanh(6, 2, 1))(xIn)_

However, I am not sure how to use _quantized_bits_ to constraint output xOut into 8-bit as well.

**Comment by zhuangh** [comment]
I see. could you replace by 

depthwise_quantizer=quantized_bits(8, 8, 1),
pointwise_quantizer=quantized_bits(8, 8, 1),
bias_quantizer=quantized_bits(8, 8, 1),

also add activation=quantized_bits(8,8,1) or other activation function you want, quantized_relu(8,8) etc,

**Comment by linbaiwpi** [comment]
> I see. could you replace by
> 
> depthwise_quantizer=quantized_bits(8, 8, 1),
> pointwise_quantizer=quantized_bits(8, 8, 1),
> bias_quantizer=quantized_bits(8, 8, 1),
> 
> also add activation=quantized_bits(8,8,1) or other activation function you want, quantized_relu(8,8) etc,

That's clear. Thanks. I'll close this issue.
