### ISSUE TITLE
Qkeras and ternary network (-1,0,1)

### ISSUE THREAD

**Issue by eejlny** [google/qkeras#51]
Is it possible to use Qkeras for training with a network where kernels are -1, 0 and 1 ?

For example in a layer as below if I set precision to 2 then I get weights -2,-1,0,1,2 and decent accuracy in the network but if I set precision to 1 all the weights become 0 and I get no accuracy at all.

        sub_model = QConv1D(512, kernel_size, input_shape=(128, 3),      
                    kernel_quantizer=quantized_bits(precision,0,symetry),
                    bias_quantizer=quantized_bits(precision,0,symetry),
                    padding='same')(main_input)

Thanks,

**Comment by zhuangh** [comment]
Hi @eejlny thank you for reaching out. could you try ternary quantizer https://github.com/google/qkeras/blob/master/qkeras/quantizers.py#L585?

**Comment by eejlny** [comment]
Thanks,

Are there any examples of how to use this ternary quantizer in a layer as below ?

I had a look but I am not sure how I should be replacing quantized_bits below with ternary. It mentions an x tensor and number of bits in the arguments.

    sub_model = QConv1D(512, kernel_size, input_shape=(128, 3),
                    kernel_quantizer=quantized_bits(precision,0,symetry),
                    bias_quantizer=quantized_bits(precision,0,symetry),
                    padding='same')(main_input)

________________________________
