### ISSUE TITLE
Is this package on pypi?

### ISSUE THREAD

**Issue by davidrpugh** [google/qkeras#53]
Thanks for the awesome work! Is this package available for install on pypi via `pip` (I couldn't find it under `qkeras`)? Or does one need to use `pip` to install from this GitHub repo directly?

**Comment by zhuangh** [comment]
Hi @davidrpugh 

sorry I missed this issue. You need to pip install it from github repo for now. We need to check the pypi package release. Thanks for the suggestion!

**Comment by zhuangh** [comment]
@danielemoro will work on this.

**Comment by zhuangh** [comment]
https://pypi.org/project/QKeras/

thanks @danielemoro
