### ISSUE TITLE
Print activation issue

### ISSUE THREAD

**Issue by FrancescoLoro** [google/qkeras#54]
Good morning I am working with your library to quantize networks.
However it is not clear to me how to print the activations out of the layers. I tried the quantized_model_debug function but it doesn't seem to output activations.

**Comment by zhuangh** [comment]
Hi @FrancescoLoro 

Check whether this function quantized_model_dump() is what you need.

https://github.com/google/qkeras/blob/master/qkeras/utils.py#L803 

An example 
https://github.com/google/qkeras/blob/724718eeb60b1ab505239c4e5f4cd417c9b9781f/examples/example_keras_to_qkeras.py#L84

**Comment by FrancescoLoro** [comment]
I have tried this methods and saves correctly the activation tensor in a binary file, but now i'm confused about how should i read that binary file in order to get my activations.
Thanks a lot!

**Comment by zhuangh** [comment]
for example, 
```python
trace_file = f"{act_name}.bin"
trace_data = np.fromfile(trace_file, dtype=np.float32)
```

**Comment by FrancescoLoro** [comment]
This works properly, thank you very much for your help!
