### ISSUE TITLE
 Assert np.mod(np.log2(negative_slope), 1) == 0 AssertionError

### ISSUE THREAD

**Issue by MichaelDee98** [google/qkeras#55]
I tried this in my code 
`x = QActivation("quantized_relu(8,0,1,0.1)")(x)` 
to make a LeakyReLU with aplha = 0.1 , but the result is
> File "qkeras/quantizers.py", line 1264, in __init__
>     assert np.mod(np.log2(negative_slope), 1) == 0
> AssertionError

This assertion does not allow parameters like 0.1, 0.2 etc. Am I using the quantized_relu wrong ?

**Comment by danielemoro** [comment]
Hello. Thank you for your question. 

The attributes for `quantized_relu` state that the `negative_slope` parameter must be a power of two. 0.1 is not power of two. (https://github.com/google/qkeras/blob/master/qkeras/quantizers.py#L1258).

Instead of 0.1, try using 0.125
