### ISSUE TITLE
Is there any way for solving quantization of batch normalization?

### ISSUE THREAD

**Issue by chizhou12306** [google/qkeras#58]
RT

**Comment by zhuangh** [comment]
Hi @chizhou12306 thank you for the question.

What do you mean by "solving quantization"? 

There are QBatchNormalization layer. 
https://github.com/google/qkeras/blob/master/qkeras/qnormalization.py

And folded Conv2D-Batch layer
https://github.com/google/qkeras/blob/master/qkeras/qconv2d_batchnorm.py#L31

**Comment by zhuangh** [comment]
feel free to reopen it.
