### ISSUE TITLE
Integer values in quantized tanh and exceeding the defined range

### ISSUE THREAD

**Issue by laurilaatu** [google/qkeras#65]
![quantized_tanh](https://user-images.githubusercontent.com/19837180/111453217-9fcbe400-8713-11eb-8859-049145abf10f.png)

Using integer part in `quantized_tanh` leads to the value going beyond the defined range of [-1,1].

Are integer bits needed for any application of the quantized tanh?

**Comment by zhuangh** [comment]
Very good point! "integer bits" here is an unfortunate name. We should rename the integer to other suitable name in order to avoid the confusion. And default mode it should be 0.

BTW, @laurilaatu thank you for working sigmoid https://github.com/google/qkeras/pull/63

**Comment by laurilaatu** [comment]
Thanks for the reply.

What would be the usage for the integer bits?
