### ISSUE TITLE
Bump version to 0.9.0

### ISSUE THREAD

**Issue by jmduarte** [google/qkeras#69]
https://github.com/google/qkeras/blob/master/qkeras/__init__.py#L39
https://github.com/google/qkeras/blob/master/setup.py#L30

It might be useful to use a package / GitHub action

**Comment by zhuangh** [comment]
thanks @jmduarte !

cc @danielemoro regarding package and GitHub action.

**Comment by zhuangh** [comment]
https://pypi.org/project/QKeras/ is added.
