### ISSUE TITLE
In Tensorflow 1.X, can't use depthwise_conv2d

### ISSUE THREAD

**Issue by shinel94** [google/qkeras#8]
in tensorflow 1.X when use depthwise_conv2d,
raise below error

AttributeError: in converted code:
    relative to C:\Users\user\Anaconda3\envs\py3_7\lib\site-packages:

    qkeras\qlayers.py:1404 call  *
        outputs = tf.keras.backend.depthwise_conv2d(
    tensorflow_core\python\util\module_wrapper.py:193 __getattr__
        attr = getattr(self._tfmw_wrapped_module, name)

    AttributeError: module 'tensorflow.python.keras.api._v2.keras.backend' has no attribute 'depthwise_conv2d'

so, Is there any room for improvement in the future for this bug?

**Comment by nunescoelho** [comment]
Which version of QKeras?

If it is 0.6, can you try to 2.1?

**Comment by shinel94** [comment]
Thank you very much for rapid answering.
Qkeras is 0.6 but i must use tf version is 1.X

**Comment by nunescoelho** [comment]
Then stick to 0.5 now.

Claudionor

**Comment by nunescoelho** [comment]
If you need batchnorm, it should not be hard to back port it to tf 1.0.

Claudionor

**Comment by shinel94** [comment]
thx 👍 :)
