### ISSUE TITLE
AutoQKeras goal definition, delta_p and delta_n

### ISSUE THREAD

**Issue by susuhu** [google/qkeras#80]
Can someone please explain delta_p and delta_n in the goal definition? 
I took this from [AutoQKeras Notebook Example](https://github.com/google/qkeras/blob/master/notebook/AutoQKeras.ipynb) and it mentioned that it allows 8% reduction in accuracy for a 2x reduction in energy. I can see that delta is the toleracne for accuracy drop and rate is for energy gain. but what's the difference/relation between delta_p and delta_n?

```python
goal = {
    "type": "energy",
    "params": {
        "delta_p": 8.0, #8% 
        "delta_n": 8.0, #8%, but difference for p and n?
        "rate": 2.0, #2 times energy saving
        "stress": 1.0,
        "process": "horowitz",
        "parameters_on_memory": ["sram", "sram"],
        "activations_on_memory": ["sram", "sram"],
        "rd_wr_on_io": [False, False],
        "min_sram_size": [0, 0],
        "source_quantizers": ["int8"], #quantizers for the input
        "reference_internal": "int8",
        "reference_accumulator": "int32"
        }
}
```

**Comment by danielemoro** [comment]
See section B on page 8 of this paper for a full explanation: https://arxiv.org/pdf/2006.10159.pdf

Also see https://github.com/google/qkeras/blob/eb6e0dc86c43128c6708988d9cb54d1e106685a4/notebook/AutoQKeras.ipynb, under the section "Quantizing a Model With AutoQKeras" for a code example and explanation
