### ISSUE TITLE
How to deploy qkeras on FPGA?

### ISSUE THREAD

**Issue by YangNuoCheng** [google/qkeras#85]
I find the 'fpga-accelerator' tag, but there's no FPGA in repository.

**Comment by vloncar** [comment]
@YangNuoCheng  You can use QKeras to train quantized models that can be mapped to fixed-precision types and deployed on FPGAs. Once such project with (almost) full compatibility with QKeras is [hls4ml](https://github.com/fastmachinelearning/hls4ml). Disclaimer: I'm one of the developers of that project.

**Comment by zhuangh** [comment]
This work https://rdcu.be/cmVO7 (published in Nature Machine Intelligence) used QKeras + hls4ml on FPGA.
