### ISSUE TITLE
TinyYOLOv3

### ISSUE THREAD

**Issue by IlkayW** [google/qkeras#9]
Is this quantization aware training suitable for any “higher” architectures like TinyYOLOv3?
I am asking, because I tried to make it work and got stuck rather early not achieving satisfying results.

**Comment by nunescoelho** [comment]
It should be. However, we have yet found a mechanism to search for how many
bits you will need for each layer. In the paper by Kurt Keutzer (HAWQ), it
was suggested that you should compute the curvature of the layers to decide
how many bits to use. Others suggested other approaches, like AutoML. So,
until we have something concrete, you have to search from more bits down to
smaller number of bits. My recommendation is to start training the network
without any constraints. Then figuring out the coefficients (for example,
you may want to determine how many bits to the left of the decimal point on
the quantizations). Remember if you set anything to the left of the decimal
point or if you use a max value in po2 quantizations, you need to set the
parameters kernel_range or bias_range, as STE based quantizers by default
clip weights between -1 and 1.

**Comment by zhuangh** [comment]
close this issue since it has been quiet for a while. feel free to reopen it if anything else comes up.
